spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/localibreport?schema=anime
    username: sa
    password: sa
logging:
  level:
    org:
      springframework:
        data:
          r2dbc: DEBUG
server:
  error:
    include-stacktrace: on_param
#  http://localhost:8080/animes/2?trace=true